language: node_js
build_image: shipimg/ubuntu1404_nodejs
node_js:
  - 0.10
before_script:
  - npm install -g jshint
script:
  - jshint
after_success:
  - if [ "$BRANCH" == "master" ] && [ "$PULL_REQUEST" == false ]; then npm version patch && git commit --amend -m "Version bump [skip_ci]" && git push git@github.com:rageshkrishna/shippable.js.git && npm publish; fi;
